name: die_bibel21
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  table_calendar: ^2.3.3
  shared_preferences: any
  url_launcher: any
  datetime_picker_formfield: 1.0.0


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
